// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Database;

#nullable disable

namespace Payments.Database.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.Domain.Capture", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentReason")
                        .HasColumnType("text")
                        .HasColumnName("adjustment_reason");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long>("OriginalFareMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("original_fare_minor");

                    b.Property<long?>("ReferralCreditId")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_credit_id");

                    b.Property<long>("ReferralCreditMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_credit_minor");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<bool>("Voided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("voided");

                    b.HasKey("Id");

                    b.HasIndex("ReferralCreditId")
                        .IsUnique()
                        .HasDatabaseName("ux_capture_referral_credit")
                        .HasFilter("referral_credit_id IS NOT NULL");

                    b.HasIndex("TripId")
                        .IsUnique()
                        .HasDatabaseName("ux_capture_trip")
                        .HasFilter("NOT voided");

                    b.ToTable("captures", (string)null);
                });

            modelBuilder.Entity("Payments.Domain.CaptureFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.ToTable("capture_failures", (string)null);
                });

            modelBuilder.Entity("Payments.Domain.CaptureIntent", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("QuoteToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_token");

                    b.Property<string>("ReferralCreditAuthority")
                        .HasColumnType("text")
                        .HasColumnName("referral_credit_authority");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("TripId");

                    b.ToTable("capture_intents", (string)null);
                });

            modelBuilder.Entity("Payments.Domain.PaymentEventOutbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<long>("CaptureId")
                        .HasColumnType("bigint")
                        .HasColumnName("capture_id");

                    b.Property<long>("CapturedAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("captured_amount_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("OriginalFareMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("original_fare_minor");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long?>("ReferralCreditId")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_credit_id");

                    b.Property<long>("ReferralCreditMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_credit_minor");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.HasKey("EventId");

                    b.HasIndex("CaptureId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_event_capture");

                    b.HasIndex("PublishedAt", "OccurredAt")
                        .HasDatabaseName("ix_payment_events_pending");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("Payments.Domain.TripEventCursor", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TripId");

                    b.ToTable("payment_trip_event_cursors", (string)null);
                });

            modelBuilder.Entity("Payments.Domain.TripEventInbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.ToTable("payment_trip_event_inbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
