// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.Service.Database;

#nullable disable

namespace Pricing.Service.Database.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pricing.Service.Domain.IssuedQuote", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Dropoff")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dropoff");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Pickup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("total_minor");

                    b.HasKey("Id");

                    b.ToTable("pricing_quotes", (string)null);
                });

            modelBuilder.Entity("Pricing.Service.Domain.MarketPressure", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AvailableDrivers")
                        .HasColumnType("integer")
                        .HasColumnName("available_drivers");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("OpenRequests")
                        .HasColumnType("integer")
                        .HasColumnName("open_requests");

                    b.HasKey("Id");

                    b.HasIndex("Market", "ObservedAt");

                    b.ToTable("market_pressure", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
