<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Common.Testing</RootNamespace>
    <AssemblyName>Common.Testing</AssemblyName>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Respawn" Version="7.0.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.12.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
  </ItemGroup>

</Project>
