// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trips.Database;

#nullable disable

namespace Trips.Database.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20260810142401_ReferralRewards")]
    partial class ReferralRewards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trips.Domain.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display");

                    b.Property<string>("Near")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("near");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Offer", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<string>("DriverId")
                        .HasColumnType("text")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("TripId", "DriverId");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.PaymentEventInbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<long>("CaptureId")
                        .HasColumnType("bigint")
                        .HasColumnName("capture_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.HasKey("EventId");

                    b.HasIndex("CaptureId")
                        .HasDatabaseName("ix_payment_event_inbox_capture");

                    b.ToTable("payment_event_inbox", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.ReferralAccount", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("RiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rider_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_account_code");

                    b.HasIndex("RiderId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_account_rider");

                    b.ToTable("referral_accounts", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.ReferralAttribution", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("FirstTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_trip_id");

                    b.Property<long?>("QualificationCaptureId")
                        .HasColumnType("bigint")
                        .HasColumnName("qualification_capture_id");

                    b.Property<string>("ReferredRiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referred_rider_id");

                    b.Property<string>("ReferrerRiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referrer_rider_id");

                    b.HasKey("Id");

                    b.HasIndex("FirstTripId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_attribution_first_trip");

                    b.HasIndex("ReferredRiderId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_attribution_referred_rider");

                    b.ToTable("referral_attributions", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.ReferralCredit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<long>("AttributionId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribution_id");

                    b.Property<string>("BeneficiaryRiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beneficiary_rider_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long?>("ReservedTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_trip_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long?>("UsedCaptureId")
                        .HasColumnType("bigint")
                        .HasColumnName("used_capture_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservedTripId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_credit_reserved_trip")
                        .HasFilter("reserved_trip_id IS NOT NULL");

                    b.HasIndex("AttributionId", "BeneficiaryRiderId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_credit_source_beneficiary");

                    b.ToTable("referral_credits", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.RiderAdmission", b =>
                {
                    b.Property<string>("RiderId")
                        .HasColumnType("text")
                        .HasColumnName("rider_id");

                    b.Property<long>("FirstTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_trip_id");

                    b.HasKey("RiderId");

                    b.HasIndex("FirstTripId")
                        .IsUnique()
                        .HasDatabaseName("ux_rider_admission_trip");

                    b.ToTable("rider_admissions", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Trip", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AssignedDriverId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_driver_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Dropoff")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dropoff");

                    b.Property<long>("FareMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("fare_minor");

                    b.Property<string>("Pickup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup");

                    b.Property<long>("QuoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("quote_id");

                    b.Property<string>("QuoteToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_token");

                    b.Property<string>("ReferralCreditAuthority")
                        .HasColumnType("text")
                        .HasColumnName("referral_credit_authority");

                    b.Property<long?>("ReferralCreditId")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_credit_id");

                    b.Property<string>("RiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rider_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_quote");

                    b.HasIndex("RiderId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_rider_active")
                        .HasFilter("state NOT IN ('completed', 'cancelled')");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.TripEventOutbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("QuoteToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_token");

                    b.Property<string>("ReferralCreditAuthority")
                        .HasColumnType("text")
                        .HasColumnName("referral_credit_authority");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.HasIndex("PublishedAt", "OccurredAt")
                        .HasDatabaseName("ix_trip_events_pending");

                    b.HasIndex("TripId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_event_version");

                    b.ToTable("trip_events", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.TripTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_state");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Id")
                        .HasDatabaseName("ix_trip_transitions_trip");

                    b.ToTable("trip_transitions", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Offer", b =>
                {
                    b.HasOne("Trips.Domain.Trip", null)
                        .WithMany("Offers")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Domain.ReferralCredit", b =>
                {
                    b.HasOne("Trips.Domain.ReferralAttribution", "Attribution")
                        .WithMany("Credits")
                        .HasForeignKey("AttributionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribution");
                });

            modelBuilder.Entity("Trips.Domain.TripTransition", b =>
                {
                    b.HasOne("Trips.Domain.Trip", null)
                        .WithMany("Transitions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Domain.ReferralAttribution", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("Trips.Domain.Trip", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
