// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trips.Database;

#nullable disable

namespace Trips.Database.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trips.Domain.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display");

                    b.Property<string>("Near")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("near");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Offer", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<string>("DriverId")
                        .HasColumnType("text")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("TripId", "DriverId");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Quote", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ConsumedByTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("consumed_by_trip");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Dropoff")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dropoff");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Pickup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("total_minor");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByTripId")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_consumer")
                        .HasFilter("consumed_by_trip IS NOT NULL");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Trip", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AssignedDriverId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_driver_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long>("FareMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("fare_minor");

                    b.Property<long>("QuoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("quote_id");

                    b.Property<string>("RiderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rider_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("RiderId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_rider_active")
                        .HasFilter("state NOT IN ('completed', 'cancelled')");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.TripTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_state");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Id")
                        .HasDatabaseName("ix_trip_transitions_trip");

                    b.ToTable("trip_transitions", (string)null);
                });

            modelBuilder.Entity("Trips.Domain.Offer", b =>
                {
                    b.HasOne("Trips.Domain.Trip", null)
                        .WithMany("Offers")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Domain.Trip", b =>
                {
                    b.HasOne("Trips.Domain.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Domain.TripTransition", b =>
                {
                    b.HasOne("Trips.Domain.Trip", null)
                        .WithMany("Transitions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Domain.Trip", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
