plugins {
    id "org.jetbrains.kotlin.jvm" version "2.2.20"
    id "application"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files("../../../../build/polyglot/jvm/azimuth-annotations")
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

application {
    mainClass = "polyglot.IdentityService"
}

kotlin {
    jvmToolchain(21)
}

test {
    useJUnitPlatform()
}
